import React,{useState} from 'react';
import {Scene,C,drawDesk,paper,folder,line,Controls,Choice,Action,Feedback,Metrics} from './desk-kit';
const sentences=['1878年，馆舍主体完工。','这里的完工不包括后来增建的侧翼。','设计师在档案中被记为De Keyser。','一份旧目录使用了缩写姓名。','建筑位于Brussels。','地址曾因街道更名而调整。','馆舍的竣工记录写于1878年。','附录列出了后续修缮事项。'];
const top=[0,2,4,6];
export function M9_1(){const[mode,setMode]=useState<'raw'|'compressed'|'dedup'>('raw'),[budget,setBudget]=useState(8);const chunks=mode==='dedup'?[0]:[0,1];const candidates=chunks.flatMap(d=>(mode==='raw'?sentences.map((_,i)=>i):top).map(i=>({d,i})));const visible=candidates.slice(0,budget);const hasContext=visible.some(x=>x.i===1);const clipped=visible.length<candidates.length; const choose=(m:typeof mode)=>setMode(m);
return <>
<Scene height={300} label="两份资料的摘要选择与全文保留" draw={(ctx,w,h)=>{drawDesk(ctx,w,h);[0,1].forEach(d=>{paper(ctx,60+d*340,24,285,232,C.blue,true);sentences.forEach((_,i)=>{const on=visible.some(x=>x.d===d&&x.i===i);ctx.fillStyle=on?(i===1?C.orange:C.blue):C.line;ctx.fillRect(86+d*340,63+i*21,205-(i%3)*23,on?6:2);if(on){ctx.fillStyle=C.green;ctx.beginPath();ctx.arc(78+d*340,66+i*21,3,0,Math.PI*2);ctx.fill();}});if(mode==='dedup'&&d===1){ctx.fillStyle='#f5f8f0c9';ctx.fillRect(62+d*340,28,280,224);line(ctx,105+d*340,84,285+d*340,212,C.orange,3);}});folder(ctx,810,77,180,137,C.green);ctx.fillStyle=C.ink;ctx.font='24px sans-serif';ctx.fillText('全文保留',840,151);ctx.fillText('2',911,193);}}/>
<Controls><Choice active={mode==='raw'} onClick={()=>choose('raw')}>完整观察</Choice><Choice active={mode==='compressed'} onClick={()=>choose('compressed')}>每份保留四句</Choice><Choice active={mode==='dedup'} onClick={()=>choose('dedup')}>四句并去重</Choice><label style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}>可见句数 <input aria-label="可见句数" type="range" min="2" max="16" value={budget} onInput={e=>setBudget(Number(e.currentTarget.value))}/><output>{budget}</output></label><Action onClick={()=>{setMode('raw');setBudget(8);}}>重置</Action></Controls>
<Metrics items={[{label:'当前显示句数',value:`${visible.length} / 16`},{label:'抑制的重复材料',value:mode==='dedup'?'1 份':'0 份'},{label:'限定语是否可见',value:hasContext?'是':'否',tone:hasContext?'good':'bad'}]}/>
<Feedback tone={clipped?'bad':!hasContext?'warn':'neutral'}>{clipped?'桌面过窄，选中的句子仍可能被裁掉；需要回看外部全文。':!hasContext?'四句摘要节省了空间，却略去了“完工”的限定条件；重点不是完整语境。':'完整观察保留了限定语，也占用了更多桌面空间。'}{mode==='dedup'?' 去重抑制的是近重复材料块；不同gold文档ID可能因此合并。':''}</Feedback>
<details style={{marginTop:16}}><summary>查看教学材料与真实预算的区别</summary><p>这里将每句算作一个演示单位，固定挑选第1、3、5、7句；不代表真实BM25分数或token数量。第二份材料是近重复版本，去重按整份材料块抑制，而不是删除同一文档的相似句。</p><div style={{display:'flex',flexWrap:'wrap',gap:16}}>{[0,1].map(d=><div key={d} style={{flex:'1 1 260px'}}><strong>材料{d+1}{mode==='dedup'&&d===1?'（整块抑制）':''}</strong><ol style={{paddingLeft:28}}>{sentences.map((s,i)=>{const shown=visible.some(x=>x.d===d&&x.i===i);return <li key={s} style={{color:shown?C.ink:C.muted}}><b>{shown?'可见':'未显示'}</b> · {s}</li>;})}</ol></div>)}</div><p>论文提示预算为30,720 tokens，另留2,048 tokens生成；压缩每份搜索结果保留4句。预算仍不足时，渲染器逐级缩减，极端情况下会退到最小上下文。来源：§2.2、第19–20页附录F。</p></details>
</>}
